language: r
r: devel
sudo: FALSE
# cache: packages

warnings_are_errors: TRUE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

r_github_packages:
  - jimhester/covr
  
after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
